video_path: res/shahin.mp4
output_dir: out/
frame_skip: 10
vehicle_classes:
  - 2 #car
  - 3 #motorcycle
  - 5 #bus
  - 7 #truck
plate_classes:
  - license_plate
model_plate: res/models/license_plate_detector.pt
model_vehicle: res/models/vehicle_detector.pt
car_detection_threshold: 0.6
plate_detection_threshold: 0.5
crop_dimension_threshold: 2400