video_path: res/shahin.mp4
output_dir: out/
frame_skip: 24
vehicle_classes:
  - car
  - bus
  - truck
  - motorcycle
plate_classes:
  - license_plate
model_plate: res/models/license_plate_detector.pt
model_vehicle: res/models/vehicle_detector.pt
iou_threshold: 0.1